const controller = require('../../src/controller/marvel_controller');
const chai = require('chai');
const expect = chai.expect;
const sinon = require('sinon');

const { expect } = require('chai');


describe('Marvel Controller', () => {
    it('Call getCredentials should return a object with timestamp and hash generated by md5', () => {
        const result = controller.getCredentials();
        expect(result).to.be.a('array')
    })

    // it('Call fetchBy should return json object', () => {
    //     const result = controller.fetchBy();
    //     expect(result).to.be.a('json');
    // })

    it('Call fetchCharacter should return a json object populated by all marvel characteres', () => {

    });

    it('Call fetchComics should return a json object populated by marvel comics', () => {

    });

    it('Call fetchEvents should return a json object populated by marvel events', () => {

    });

    it('Call fetchSeries should return a json object populated by marvel series', () => {

    });

    it('Call fetchStories should return a json object populated by marvel stories', () => {

    });
});