const controller = require('../../src/controller/marvel_controller');
const chai = require('chai');
const sinon = require('sinon');

const { expect } = require('chai');


describe('Marvel Controller', () => {
    it('Call getCredentials should return a object with timestamp and hash generated by md5', () => {
        const result = controller.getCredentials();
        expect(result).to.be.a('array')
    })

    // it('Call fetchBy should return statusCode 200', () => {
    //     const res = {};
    //     res.status = () => res;
    //     res.send = sinon.spy();

    //     expect(res.send).to.be.equal(200)
    // })
});